"""initial

Revision ID: 0de1443cd0f2
Revises: 
Create Date: 2026-05-05 07:44:39.325018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0de1443cd0f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('jobs',
        sa.Column(
            'id',
            sa.String(),
            server_default=sa.text("gen_random_uuid()::text"),
            nullable=False,
        ),
        sa.Column('pdf_filename', sa.String(), nullable=False),
        sa.Column('pdf_path', sa.String(), nullable=False),
        sa.Column(
            'status',
            sa.String(),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            'result',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'completed', 'failed', 'cancelled')",
            name='ck_jobs_status',
        ),
    )
    op.create_index('idx_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index(
        'idx_jobs_status_created',
        'jobs',
        ['status', 'created_at'],
        unique=False,
        postgresql_where="status = 'pending'",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_jobs_status_created', table_name='jobs', postgresql_where="status = 'pending'")
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_jobs_created_at', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
